const cfg = window.SILVERLINE_CONFIG || {};
const configured = cfg.supabaseUrl && !cfg.supabaseUrl.includes('YOUR_') && cfg.supabasePublishableKey && !cfg.supabasePublishableKey.includes('YOUR_');
const client = configured ? window.supabase.createClient(cfg.supabaseUrl, cfg.supabasePublishableKey) : null;
const state={properties:[]};
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(n,c='$')=>`${c}${Number(n||0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
function card(p){const img=(p.image_urls||[])[0]||'assets/silverline-logo.png';return `<article class="card"><div class="photo" style="background-image:linear-gradient(rgba(20,20,15,.05),rgba(20,20,15,.18)),url('${escapeHtml(img)}')"><span>Silverline</span></div><div class="card-body"><p class="meta">Community Property</p><h3>${escapeHtml(p.name)}</h3><p class="price">${money(p.price,p.currency)}</p><p>${escapeHtml((p.description||'').slice(0,180))}${(p.description||'').length>180?'…':''}</p><a href="property.html?id=${encodeURIComponent(p.id)}">View property →</a></div></article>`}
async function load(){const box=document.getElementById('properties'),loading=document.getElementById('loading');if(!client){loading.textContent='Connect Supabase in config.js to load live properties.';document.getElementById('resultCount').textContent='';return}const {data,error}=await client.from('properties').select('*').eq('published',true).order('created_at',{ascending:false});loading.hidden=true;if(error){loading.hidden=false;loading.textContent='Unable to load properties right now.';console.error(error);return}state.properties=data||[];render(state.properties)}
function render(list){const box=document.getElementById('properties');box.innerHTML=list.map(card).join('');document.getElementById('resultCount').textContent=`${list.length} ${list.length===1?'property':'properties'}`;document.getElementById('empty').hidden=list.length!==0}
function filter(){const q=document.getElementById('search').value.trim().toLowerCase(),t=document.getElementById('type').value;render(state.properties.filter(p=>(!q||`${p.name} ${p.description}`.toLowerCase().includes(q))&&(!t||true)))}
document.getElementById('searchBtn').addEventListener('click',filter);document.getElementById('search').addEventListener('keydown',e=>{if(e.key==='Enter')filter()});document.getElementById('type').addEventListener('change',filter);load();